# Generated by Django 3.2 on 2021-05-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZOO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('total_area', models.FloatField(default=3.4)),
            ],
        ),
        migrations.CreateModel(
            name='Aviary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField()),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aviaries', to='main.zoo')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('required_area', models.FloatField()),
                ('aviary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='main.aviary')),
            ],
        ),
    ]
