# Generated by Django 3.2 on 2021-05-06 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='unit',
            field=models.CharField(choices=[('km2', 'Square kilometre'), ('m2', 'Square metre')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aviary',
            name='unit',
            field=models.CharField(choices=[('km2', 'Square kilometre'), ('m2', 'Square metre')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoo',
            name='unit',
            field=models.CharField(choices=[('km2', 'Square kilometre'), ('m2', 'Square metre')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
