# Generated by Django 3.2 on 2021-05-06 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210506_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviary',
            name='typeOfAnimals',
            field=models.CharField(choices=[('lion', 'lion'), ('monkey', 'monkey'), ('tiger', 'tiger'), ('elephant', 'elephant')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
