# Generated by Django 3.2 on 2021-05-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210506_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviary',
            name='free_area',
            field=models.IntegerField(),
        ),
    ]
