# Generated by Django 3.2 on 2021-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_zoo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='free_area',
            field=models.FloatField(default=0.0),
        ),
    ]
