# Generated by Django 3.2 on 2021-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_zoo_free_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviary',
            name='free_area',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aviary',
            name='occupied_place',
            field=models.FloatField(default=0),
        ),
    ]
